# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build & Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build site
      run: |
        make publish

    - name: Setup ~/.ssh
      run: |
        mkdir -p ~/.ssh/
        echo 'c.w6.io ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDI1l1Q99jHAk1dRvD+87B6MqvJhoNlhJAa2S32UM/cvjjR/NIYJUMjQ4fYDiL8yeQN7RHItO9vQWWPXZS4risyCXGblefdqxgXWxObgFebFUBR/xpBZQoO0+KNO45DzjuatXwonV6ITCv+YWKcAD6CFYGvqKik3zvIrkiH+0HoXNVQL2smXC+R7zLApfYl7l4hcFOz8mMVSvGZcV2LLkPvjuupkSXxBHktvyaXoFzknYES+1xGs0/o1uRGWnc091ImpVYNlz+GKtnESmm0XFFqz2MuIhCvXBoxyxANisYP7NcmOCZ3fcAFk57YviRN7UEMeFMFY4Qd442CRutPeRUdwlvn/lEJyyUK+ruKcPERTbUsqJLGh0Ff31tQKN0VY1XnKFTHJCevM0Ga77xkrEfXMkiST3Q931jPxDyu0RHW6fbyKAzpP5aQPeB4JPpq6RuaKYOFSx4QDg0vKGLOH0ViKz29iMmNCRlNZ+HTAH0W+vYwNfNDKPPLTtcG4/sEsNc=' > ~/.ssh/known_hosts

    - name: Decrypt ssh key
      env:
        SYMMETRICAL_KEY: ${{ secrets.SYMMETRICAL_KEY }}
        NOT_SECRET: ${{ secrets.NOT_SECRET }}
      run: |
        echo "not a secret: $NOT_SECRET"
        echo $NOT_SECRET
        openssl enc -d -aes-256-cbc -pbkdf2 -in ./id_rsa_webupdate.aes -out ./id_rsa_webupdate --pass pass:$SYMMETRICAL_KEY
        chmod 600 ./id_rsa_webupdate

    - name: Push site contents
      run: |
        head -n 1 ./id_rsa_webupdate
        echo "put -r ./content/ ./vicsimeone/" | sftp -i ./id_rsa_webupdate webupdate@c.w6.io
